name: chessmate
description: A chess tournament management program.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yaru: ^8.0.0
  handy_window: ^0.4.0
  freezed_annotation: ^3.0.0
  fast_immutable_collections: ^11.0.4
  path_provider: ^2.1.1
  sqflite_common_ffi: ^2.3.4
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  fpdart: ^1.1.1
  path: ^1.9.1
  watch_it: ^1.6.5
  get_it: ^8.0.3
  safe_change_notifier: ^0.4.0
  go_router: ^16.0.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^3.0.6
  analyzer: ^8.0.0
  drift_dev: ^2.21.2

flutter:
  uses-material-design: true
  generate: true
