name: chessmatey
description: A chess tournament management program.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yaru: ^5.3.1
  handy_window: ^0.4.0
  freezed_annotation: ^2.4.1
  fast_immutable_collections: ^10.1.1
  path_provider: ^2.1.1
  hooks_riverpod: ^2.4.6
  flutter_hooks: ^0.20.3
  riverpod_annotation: ^2.3.1
  flutter_riverpod: ^2.4.10
  sqflite_common_ffi: ^2.3.4
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  fpdart: ^1.1.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  riverpod_generator: ^2.3.6
  custom_lint: ^0.6.0
  analyzer: ^6.7.0
  drift_dev: ^2.21.2

flutter:
  uses-material-design: true
